# Generated by Django 2.2.6 on 2019-12-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_reservation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='datetime_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
