# Generated by Django 2.2.6 on 2019-12-15 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20191215_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='datetime_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 15, 21, 34, 33, 936143)),
            preserve_default=False,
        ),
    ]
