# Generated by Django 2.2.6 on 2019-12-20 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20191219_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_worker',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='car_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.CarInstance'),
        ),
    ]
