# Generated by Django 2.2.6 on 2020-01-04 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20191220_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
